#!/bin/bash

## give a name to your job
#SBATCH --job-name=NEURONPAP_RyoN

#SBATCH --mail-type=END,FAIL
## your contact email
#SBATCH --mail-user=ryo.nakatani@oist.jp

## number of cores for your simulation,
## for parallel job array about 20
#SBATCH --ntasks=50

## Save output file as seed and endt name
#SBATCH --output=../outLog/simTripytite_%j.out

## you can replace compute with short if your simulation time is below 1 day
#SBATCH --partition=short

## how much memory per core
#SBATCH --mem-per-cpu=4g

## maximum time for your simulation, in DAY-HOUR:MINUTE:SECOND
#SBATCH --time=0-12:0:0

## load modules
module use /apps/unit/DeSchutterU/.modulefiles
module load python/3.7.3
module load neuron/py3_7.7


## Echo Stats
echo "Running job" $SLURM_JOB_ID
echo "Using N processes:" $SLURM_NTASKS

mpirun -n $SLURM_NTASKS python NEURONPAP.py -c
