[project]
name = "NEURONPAP"
version = "0.1.0"
description = "Astrocyte conductance-based model implemented in NEURON"
requires-python = "==3.10.*"
dependencies = [
    "matplotlib>=3.10.3",
    "memory-profiler>=0.61.0",
    "mpi4py>=4.1.1",
    "neuron==8.2.7",
    "pandas>=2.3.0",
    "scipy>=1.15.3",
    "statsmodels>=0.14.6",
    "tqdm>=4.67.1",
]
